### ISSUE TITLE
Few random issues

### ISSUE THREAD

**Issue by Mango0x45** [RaulCotar/rayalloc#2]
So I thought this was kind of cool so I cloned and tried to build it on
MacOS.  The build failed, and there were a few issues I’ll list here in
case you ever decide you want to support Apple:

1. dprintf() conflicts with the dprintf() in Apples <stdio.h>.  I would
   imagine this shouldn’t matter since it’s a macro, but I do get the
   following warning:

    ```
    In file included from src/rayalloc.c:6:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:362:5: error: expected parameter declarator
    int     dprintf(int, const char * __restrict, ...) __printflike(2, 3) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
    ```

2. C23 disallows the use of alignas() in type-definitions.  This renders
   the following typedef invalid:

    ```c
    typedef struct alignas(16) array {
        u32 flags;
        u32 cap, len;
        u32 ref;
        char data[];
    } ar_t;
    ```

3. The definitions for i8, i16, …, u64 should be using the fixed-width
   integer types from <stdint.h>.  I’ve opened a PR for that.

4. mremap() doesn’t exist on MacOS

5. MAP_SHARED_VALIDATE doesn’t exist on MacOS

**Comment by RaulCotar** [comment]
1. I replaced `dprintf` with a nicer, still macro-based debug printing system
2. Fixed that `alignas`
3. Merged that PR
4. that's annoying since it seems `MAP_FIXED_NOREPLACE` is also not available. I'm thinking of ways to handle that, but it's not high priority since the map resizing feature is not used at the moment anyway.
5. Should be fixable with a bit of macro trickery

All the changed outlined above are in the `testing` branch. Note that no executable binary compiles on that branch at the moment.
